/* All document processing stays in this browser. No upload endpoint. */
'use strict';
pdfjsLib.GlobalWorkerOptions.workerSrc='./vendor/pdf.worker.min.js';
const D={angle:0,brightness:100,contrast:100,sharpness:0,clean:0,mode:'color',framing:'keep'};
const $=id=>document.getElementById(id);
let pdf=null,inputBytes=null,count=0,page=0,config={},name='',timer,seq=0,busy=false,baseCanvas=null,masks={},previewMeta=null,drag=null;
function status(s){$('status').textContent=s}
function current(){return config[page]||{...D}}
function progress(title,done,total,detail=''){let percent=Math.round(done/Math.max(1,total)*100);$('progressOverlay').hidden=false;$('progressTitle').textContent=title;$('progressDetail').textContent=detail||`${done} / ${total} 페이지`;$('progressPercent').textContent=percent+'%';$('progressBar').style.width=percent+'%';$('progressTrack').setAttribute('aria-valuenow',percent)}
function finishProgress(){$('progressOverlay').hidden=true}
function locked(v){busy=v;$('controls').inert=v;$('pages').inert=v;$('controls').classList.toggle('busy',v);$('upload').disabled=v;$('prev').disabled=v||!pdf||page===0;$('next').disabled=v||!pdf||page===count-1;$('pages').classList.toggle('busy',v)}
function controls(){let s=current();for(let k of Object.keys(D))$(k).value=s[k];$('angleRange').value=s.angle;for(let k of ['brightness','contrast','sharpness','clean'])$(k+'Value').textContent=s[k]+(['brightness','contrast'].includes(k)?'%':'');$('framingHint').textContent={keep:'내용을 축소하지 않습니다. 용지 밖 가장자리는 잘릴 수 있으니 미리보기로 확인하세요.',expand:'내용 크기를 유지하고 용지를 넓힙니다. 인쇄할 때 실제 크기를 선택하세요.',fit:'전체 모서리를 원래 용지에 맞춥니다. 각도가 커질수록 내용이 작아집니다.'}[s.framing];$('pageTitle').textContent=`${page+1} / ${count} 페이지`;for(let el of $('pages').children){let i=+el.dataset.page;el.classList.toggle('active',i===page);el.classList.toggle('changed',JSON.stringify(config[i]||D)!==JSON.stringify(D)||(masks[i]||[]).length>0)}locked(busy)}
function canvas(w,h){let c=document.createElement('canvas');c.width=w;c.height=h;return c}
async function render(i,dpi,preview=false){let p=await pdf.getPage(i+1),v=p.getViewport({scale:1});let scale=dpi/72;if(preview)scale=Math.min(scale,1500/Math.max(v.width,v.height));let vp=p.getViewport({scale});if(vp.width*vp.height>25000000)throw Error('페이지가 너무 큽니다. 저장 품질을 낮춰 주세요.');let c=canvas(Math.ceil(vp.width),Math.ceil(vp.height));await p.render({canvasContext:c.getContext('2d'),viewport:vp,background:'white'}).promise;return {c,width:v.width,height:v.height}}
function boxBlur(gray,w,h,r){let temp=new Float32Array(w*h),out=new Float32Array(w*h);for(let y=0;y<h;y++){let sum=0;for(let x=-r;x<=r;x++)sum+=gray[y*w+Math.max(0,Math.min(w-1,x))];for(let x=0;x<w;x++){temp[y*w+x]=sum/(2*r+1);sum+=gray[y*w+Math.min(w-1,x+r+1)]-gray[y*w+Math.max(0,x-r)]}}for(let x=0;x<w;x++){let sum=0;for(let y=-r;y<=r;y++)sum+=temp[Math.max(0,Math.min(h-1,y))*w+x];for(let y=0;y<h;y++){out[y*w+x]=sum/(2*r+1);sum+=temp[Math.min(h-1,y+r+1)*w+x]-temp[Math.max(0,y-r)*w+x]}}return out}
function process(src,s,index=page){let c=canvas(src.width,src.height),ctx=c.getContext('2d');ctx.drawImage(src,0,0);let image=ctx.getImageData(0,0,c.width,c.height),a=image.data,w=c.width,h=c.height;
 if(s.clean||s.brightness!==100||s.contrast!==100||s.sharpness||s.mode!=='color'){
  let gray=null,bg=null;
  if(s.clean){gray=new Float32Array(w*h);for(let i=0,j=0;i<a.length;i+=4,j++)gray[j]=.299*a[i]+.587*a[i+1]+.114*a[i+2];bg=boxBlur(gray,w,h,Math.max(5,Math.round(w/60)))}
  let amount=s.clean/100,b=s.brightness/100,k=s.contrast/100;
  for(let i=0,j=0;i<a.length;i+=4,j++){
   for(let z=0;z<3;z++){let value=a[i+z];if(bg)value=value*(1-amount)+Math.min(255,value*255/Math.max(100,bg[j]))*amount;a[i+z]=Math.max(0,Math.min(255,(value*b-128)*k+128))}
   if(s.mode!=='color'){let value=.299*a[i]+.587*a[i+1]+.114*a[i+2];if(s.mode==='bw')value=value>175?255:0;a[i]=a[i+1]=a[i+2]=value}
  }
  if(s.sharpness){let original=new Uint8ClampedArray(a),strength=s.sharpness/100;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let i=(y*w+x)*4;for(let z=0;z<3;z++){let mean=(original[i-4+z]+original[i+4+z]+original[i-w*4+z]+original[i+w*4+z])/4;a[i+z]=original[i+z]+strength*(original[i+z]-mean)}}}
  ctx.putImageData(image,0,0);
 }
 for(let region of masks[index]||[]){let points=region.points.map(([x,y])=>[x*w,y*h]);let x=Math.max(0,Math.floor(Math.min(...points.map(p=>p[0])))),y=Math.max(0,Math.floor(Math.min(...points.map(p=>p[1])))),right=Math.min(w,Math.ceil(Math.max(...points.map(p=>p[0])))),bottom=Math.min(h,Math.ceil(Math.max(...points.map(p=>p[1]))));if(right<=x||bottom<=y)continue;ctx.save();ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.clip();if(region.kind==='black'){ctx.fillStyle='black';ctx.fillRect(x,y,right-x,bottom-y)}else{let block=Math.max(8,Math.round(w/65)),tiny=canvas(Math.max(1,Math.ceil((right-x)/block)),Math.max(1,Math.ceil((bottom-y)/block)));tiny.getContext('2d').drawImage(c,x,y,right-x,bottom-y,0,0,tiny.width,tiny.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(tiny,x,y,right-x,bottom-y)}ctx.restore()}
 if(Math.abs(s.angle)<.001)return c;
 let rad=s.angle*Math.PI/180,ow=Math.ceil(w*Math.abs(Math.cos(rad))+h*Math.abs(Math.sin(rad))),oh=Math.ceil(w*Math.abs(Math.sin(rad))+h*Math.abs(Math.cos(rad)));
 let out=canvas(s.framing==='expand'?ow:w,s.framing==='expand'?oh:h),o=out.getContext('2d');o.fillStyle='white';o.fillRect(0,0,out.width,out.height);o.translate(out.width/2,out.height/2);if(s.framing==='fit'){let factor=Math.min(w/ow,h/oh);o.scale(factor,factor)}o.rotate(rad);o.drawImage(c,-w/2,-h/2);return out;
}
async function preview(load=false){if(!pdf)return;let n=++seq;try{if(load||!baseCanvas){let r=await render(page,100,true);if(n!==seq)return;baseCanvas=r.c;$('original').src=baseCanvas.toDataURL('image/jpeg',.9);$('original').hidden=false}let s={...current()},out=process(baseCanvas,s);if(n!==seq)return;previewMeta={width:baseCanvas.width,height:baseCanvas.height,outWidth:out.width,outHeight:out.height,settings:s};$('corrected').src=out.toDataURL('image/jpeg',.9);$('corrected').hidden=false;$('maskCount').textContent=`현재 페이지 ${ (masks[page]||[]).length }개 영역`;}catch(e){status(e.message)}}
function change(k,v){if(!pdf||busy)return;config[page]={...current(),[k]:['mode','framing'].includes(k)?v:Math.max(+$(k).min,Math.min(+$(k).max,+v||0))};controls();clearTimeout(timer);timer=setTimeout(()=>preview(),100)}
for(let k of Object.keys(D))$(k).addEventListener('input',e=>change(k,e.target.value));$('angleRange').oninput=e=>change('angle',e.target.value);$('minus').onclick=()=>change('angle',+(current().angle-.1).toFixed(2));$('plus').onclick=()=>change('angle',+(current().angle+.1).toFixed(2));$('grid').onchange=e=>document.querySelectorAll('.paper').forEach(p=>p.classList.toggle('grid',e.target.checked));
async function go(i){if(busy)return;clearTimeout(timer);page=i;baseCanvas=null;controls();await preview(true)}$('prev').onclick=()=>go(Math.max(0,page-1));$('next').onclick=()=>go(Math.min(count-1,page+1));
$('upload').onchange=async e=>{let f=e.target.files[0];if(!f)return;if(f.size>250*1024*1024){status('파일은 250MB 이하로 선택해 주세요.');return}locked(true);status('브라우저에서 PDF를 읽는 중…');try{let bytes=new Uint8Array(await f.arrayBuffer());await PDFLib.PDFDocument.load(bytes);let next=await pdfjsLib.getDocument({data:bytes.slice(),isEvalSupported:false}).promise;if(pdf)await pdf.destroy();pdf=next;inputBytes=bytes;count=pdf.numPages;page=0;config={};masks={};baseCanvas=null;previewMeta=null;name=f.name;$('filename').textContent=name;$('filename').style.wordBreak='break-all';$('pages').replaceChildren();for(let i=0;i<count;i++){let b=document.createElement('button');b.textContent=`${i+1} 페이지`;b.dataset.page=i;b.onclick=()=>go(i);$('pages').appendChild(b)}$('empty').hidden=$('empty2').hidden=true;controls();await preview(true);status(`${count}페이지를 열었습니다. 파일은 서버에 전송되지 않습니다.`)}catch(e){status(/encrypt|password/i.test(e.message)?'암호가 걸린 PDF는 암호를 해제한 사본을 넣어 주세요.':'PDF 열기 실패: '+e.message)}finally{locked(false);e.target.value=''}};
function yieldUI(){return new Promise(r=>setTimeout(r,0))}
async function deskew(src){let scale=Math.min(1,700/Math.max(src.width,src.height)),w=Math.round(src.width*scale),h=Math.round(src.height*scale),c=canvas(w,h),ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(src,0,0,w,h);let a=ctx.getImageData(0,0,w,h).data,points=[];for(let y=Math.ceil(h/30);y<h-h/30;y++)for(let x=Math.ceil(w/30);x<w-w/30;x++){let i=(y*w+x)*4;if(.299*a[i]+.587*a[i+1]+.114*a[i+2]<165)points.push([x-w/2,y-h/2])}if(points.length<150)return 0;
 function score(deg){let rad=deg*Math.PI/180,co=Math.cos(rad),si=Math.sin(rad),rows=new Float32Array(h+Math.ceil(w*.2)+10),offset=rows.length/2;for(let [x,y] of points){let row=Math.round(x*si+y*co+offset);if(row>0&&row<rows.length)rows[row]++}let sum=0;for(let i=1;i<rows.length;i++)sum+=(rows[i]-rows[i-1])**2;return sum/rows.length}
 let best=0,value=score(0),baseline=value;for(let angle=-5;angle<=5.001;angle+=.25){let scoreValue=score(angle);if(scoreValue>value){value=scoreValue;best=angle}}let center=best;for(let angle=Math.max(-5,center-.25);angle<=Math.min(5,center+.25)+.001;angle+=.05){let scoreValue=score(angle);if(scoreValue>value){value=scoreValue;best=angle}}return value<baseline*1.04||Math.abs(best)<.075?0:+best.toFixed(2);
}
// Sample paper backgrounds tile by tile; limit enhancement for photos and coloured marks.
function analysePixels(a,w,h){
 const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
 const hist=new Uint32Array(256),tiles=Array.from({length:64},()=>new Uint32Array(256)),sizes=new Uint32Array(64);
 let total=0,coloured=0;
 for(let y=Math.floor(h*.03);y<h*.97;y++)for(let x=Math.floor(w*.03);x<w*.97;x++){
  let i=(y*w+x)*4,r=a[i],g=a[i+1],b=a[i+2],v=Math.round(.299*r+.587*g+.114*b),t=Math.min(7,Math.floor(y/h*8))*8+Math.min(7,Math.floor(x/w*8));
  hist[v]++;tiles[t][v]++;sizes[t]++;total++;
  if(Math.max(r,g,b)-Math.min(r,g,b)>35&&v<225)coloured++;
 }
 function percentile(h,n,q){let sum=0;for(let i=0;i<256;i++){sum+=h[i];if(sum>=n*q)return i}return 255}
 let backgrounds=tiles.map((h,i)=>sizes[i]?percentile(h,sizes[i],.8):null).filter(v=>v!==null).sort((a,b)=>a-b);
 let bg=backgrounds[Math.floor(backgrounds.length*.65)]??255,spread=backgrounds[Math.floor(backgrounds.length*.9)]-backgrounds[Math.floor(backgrounds.length*.1)];
 let inkHist=new Uint32Array(256),inkCount=0;for(let v=0;v<bg-28;v++){inkHist[v]=hist[v];inkCount+=hist[v]}
 let ink=inkCount?percentile(inkHist,inkCount,.25):bg,coverage=inkCount/Math.max(1,total),colour=coloured/Math.max(1,total);
 if(coverage>.32||colour>.18||bg<145)return {brightness:100,contrast:100,sharpness:0,clean:0,kind:'사진·어두운 페이지: 원본 유지'};
 if(bg>=247&&spread<12&&(!inkCount||percentile(inkHist,inkCount,.05)<85))return {brightness:100,contrast:100,sharpness:0,clean:0,kind:'깨끗한 페이지: 원본 유지'};
 let clean=Math.round(clamp((245-bg)*.55+Math.max(0,spread-8)*.55,0,45));
 if(colour>.002)clean=Math.min(clean,25);
 let amount=clean/100,effectiveBg=bg+(255-bg)*amount,effectiveInk=ink*(1-amount)+Math.min(255,ink*255/Math.max(100,bg))*amount;
 let k=inkCount?clamp(215/Math.max(1,effectiveBg-effectiveInk),1,colour>.002?1.15:1.4):1;
 let brightness=Math.round(clamp((245-128+128*k)/(Math.max(1,effectiveBg)*k)*100,100,colour>.002?115:125));
 let contrast=Math.round(k*100),sharpness=inkCount?Math.round(clamp((ink-65)*.2,0,colour>.002?12:25)):0;
 return {brightness,contrast,sharpness,clean,kind:'페이지 상태 분석 완료'};
}
function analysePage(src){let scale=Math.min(1,900/Math.max(src.width,src.height)),c=canvas(Math.max(1,Math.round(src.width*scale)),Math.max(1,Math.round(src.height*scale))),ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(src,0,0,c.width,c.height);return analysePixels(ctx.getImageData(0,0,c.width,c.height).data,c.width,c.height)}
function analysedSettings(src,settings){let {kind,...values}=analysePage(src);return {...settings,...values}}
async function automatic(all,quick=false){if(!pdf||busy)return;locked(true);clearTimeout(timer);try{let targets=all?Array.from({length:count},(_,i)=>i):[page],shared={mode:current().mode,framing:current().framing};progress(quick?'전체 문서 원클릭 보정':'자동 기울기 보정',0,targets.length);await yieldUI();for(let i=0;i<targets.length;i++){progress(quick?'전체 문서 원클릭 보정':'자동 기울기 보정',i,targets.length,`${i+1} / ${targets.length} 페이지 · ${quick?'화질과 기울기':'기울기'} 분석 중`);await yieldUI();let {c}=await render(targets[i],100,true),settings={...(config[targets[i]]||D)};if(quick)settings=analysedSettings(c,{...settings,...shared});let angle=await deskew(c);config[targets[i]]={...settings,angle};progress(quick?'전체 문서 원클릭 보정':'자동 기울기 보정',i+1,targets.length);await yieldUI()}controls();await preview();status(quick?'페이지별 화질 분석과 자동 기울기 보정 완료. 연한 글씨·도장을 확인한 후 저장하세요.':'자동 기울기 보정 완료. 글줄과 표를 보고 결과를 확인하세요.')}catch(e){status(e.message)}finally{finishProgress();locked(false)}}$('auto').onclick=()=>automatic(false);$('autoAll').onclick=()=>automatic(true);$('quickClean').onclick=()=>automatic(true,true);
$('cleanPreset').onclick=async()=>{if(!pdf||busy)return;locked(true);clearTimeout(timer);progress('현재 페이지 자동 정리',0,1,'배경 밝기와 글자 대비를 분석하고 있습니다…');try{await yieldUI();let {c}=await render(page,100,true),analysis=analysePage(c),{kind,...values}=analysis;config[page]={...current(),...values};controls();await preview();status(`${kind} · 밝기 ${values.brightness}% / 대비 ${values.contrast}% / 선명도 ${values.sharpness} / 배경 ${values.clean}. 연한 글씨·도장을 확인하세요.`)}catch(e){status(e.message)}finally{finishProgress();locked(false)}};
$('applyAll').onclick=()=>{if(!pdf)return;let s={...current()};for(let i=0;i<count;i++)config[i]={...s};controls();preview();status('각도를 포함한 현재 설정을 전체에 적용했습니다.')};$('reset').onclick=()=>{if(!pdf)return;delete config[page];delete masks[page];controls();preview();status('현재 페이지 원본 설정으로 복귀')};$('resetAll').onclick=()=>{if(!pdf)return;config={};masks={};controls();preview();status('전체 페이지 원본 설정으로 복귀')};
$('save').onclick=async()=>{if(!pdf||busy)return;locked(true);clearTimeout(timer);progress('PDF 저장 중',0,count+1,'문서를 준비하고 있습니다…');try{await yieldUI();let source=await PDFLib.PDFDocument.load(inputBytes),out=await PDFLib.PDFDocument.create();for(let i=0;i<count;i++){progress('PDF 저장 중',i,count+1,`${i+1} / ${count} 페이지 처리 중`);await yieldUI();let s=config[i]||D;if(JSON.stringify(s)===JSON.stringify(D)&&!(masks[i]||[]).length){let [p]=await out.copyPages(source,[i]);out.addPage(p);continue}let r=await render(i,+$('dpi').value),c=process(r.c,s,i),image=await out.embedPng(c.toDataURL('image/png')),w=r.width,h=r.height;if(s.framing==='expand'){w*=c.width/r.c.width;h*=c.height/r.c.height}let p=out.addPage([w,h]);p.drawImage(image,{x:0,y:0,width:w,height:h});progress('PDF 저장 중',i+1,count+1);await yieldUI()}progress('PDF 저장 중',count,count+1,'모든 페이지 처리 완료 · PDF 파일을 묶는 중…');await yieldUI();let bytes=await out.save(),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');progress('PDF 저장 완료',count+1,count+1,'다운로드가 시작됩니다.');await yieldUI();a.href=url;a.download=name.replace(/\.pdf$/i,'')+'_보정.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status('완료! 다운로드 폴더에서 보정된 PDF를 확인하세요.')}catch(e){status('저장 실패: '+e.message)}finally{finishProgress();locked(false)}};
function pointOnImage(e){let r=$('corrected').getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]}
function drawSelection(a,b){let r=$('corrected').getBoundingClientRect(),parent=$('correctedPaper').getBoundingClientRect(),el=$('mosaicSelection');el.hidden=false;el.style.left=(r.left-parent.left+Math.min(a[0],b[0])*r.width)+'px';el.style.top=(r.top-parent.top+Math.min(a[1],b[1])*r.height)+'px';el.style.width=(Math.abs(a[0]-b[0])*r.width)+'px';el.style.height=(Math.abs(a[1]-b[1])*r.height)+'px'}
function toOriginal([x,y],meta){let s=meta.settings,rad=s.angle*Math.PI/180,co=Math.cos(rad),si=Math.sin(rad),ow=Math.ceil(meta.width*Math.abs(co)+meta.height*Math.abs(si)),oh=Math.ceil(meta.width*Math.abs(si)+meta.height*Math.abs(co)),factor=s.framing==='fit'?Math.min(meta.width/ow,meta.height/oh):1;let px=(x*meta.outWidth-meta.outWidth/2)/factor,py=(y*meta.outHeight-meta.outHeight/2)/factor;return [(px*co+py*si+meta.width/2)/meta.width,(-px*si+py*co+meta.height/2)/meta.height]}
$('mosaicMode').onchange=e=>$('correctedPaper').classList.toggle('mosaic-mode',e.target.checked);
$('corrected').onpointerdown=e=>{if(!pdf||busy||!$('mosaicMode').checked||!previewMeta)return;e.preventDefault();$('corrected').setPointerCapture(e.pointerId);drag={start:pointOnImage(e),meta:previewMeta,page};drawSelection(drag.start,drag.start)};
$('corrected').onpointermove=e=>{if(drag)drawSelection(drag.start,pointOnImage(e))};
$('corrected').onpointerup=e=>{if(!drag)return;let d=drag,end=pointOnImage(e);drag=null;$('mosaicSelection').hidden=true;if(Math.abs(d.start[0]-end[0])<.005||Math.abs(d.start[1]-end[1])<.005)return;let [x1,y1]=d.start,[x2,y2]=end,points=[[x1,y1],[x2,y1],[x2,y2],[x1,y2]].map(p=>toOriginal(p,d.meta));(masks[d.page]||=([])).push({points,kind:$('maskKind').value});controls();preview();status('선택 영역을 가렸습니다. PDF 저장 결과에도 적용됩니다.')};
$('corrected').onpointercancel=()=>{drag=null;$('mosaicSelection').hidden=true};
$('undoMask').onclick=()=>{if(!pdf)return;(masks[page]||[]).pop();controls();preview()};$('clearMasks').onclick=()=>{if(!pdf)return;delete masks[page];controls();preview()};
