/* All document processing stays in this browser. No upload endpoint. */
'use strict';
pdfjsLib.GlobalWorkerOptions.workerSrc='./vendor/pdf.worker.min.js';
const D={angle:0,brightness:100,contrast:100,sharpness:0,clean:0,mode:'color',framing:'keep'};
const $=id=>document.getElementById(id);
let pdf=null,inputBytes=null,count=0,page=0,config={},name='',timer,seq=0,busy=false,baseCanvas=null;
function status(s){$('status').textContent=s}
function current(){return config[page]||{...D}}
function locked(v){busy=v;$('controls').classList.toggle('busy',v);$('upload').disabled=v;$('prev').disabled=v||!pdf||page===0;$('next').disabled=v||!pdf||page===count-1;$('pages').classList.toggle('busy',v)}
function controls(){let s=current();for(let k of Object.keys(D))$(k).value=s[k];$('angleRange').value=s.angle;for(let k of ['brightness','contrast','sharpness','clean'])$(k+'Value').textContent=s[k]+(['brightness','contrast'].includes(k)?'%':'');$('framingHint').textContent={keep:'내용을 축소하지 않습니다. 용지 밖 가장자리는 잘릴 수 있으니 미리보기로 확인하세요.',expand:'내용 크기를 유지하고 용지를 넓힙니다. 인쇄할 때 실제 크기를 선택하세요.',fit:'전체 모서리를 원래 용지에 맞춥니다. 각도가 커질수록 내용이 작아집니다.'}[s.framing];$('pageTitle').textContent=`${page+1} / ${count} 페이지`;for(let el of $('pages').children){let i=+el.dataset.page;el.classList.toggle('active',i===page);el.classList.toggle('changed',JSON.stringify(config[i]||D)!==JSON.stringify(D))}locked(busy)}
function canvas(w,h){let c=document.createElement('canvas');c.width=w;c.height=h;return c}
async function render(i,dpi,preview=false){let p=await pdf.getPage(i+1),v=p.getViewport({scale:1});let scale=dpi/72;if(preview)scale=Math.min(scale,1500/Math.max(v.width,v.height));let vp=p.getViewport({scale});if(vp.width*vp.height>25000000)throw Error('페이지가 너무 큽니다. 저장 품질을 낮춰 주세요.');let c=canvas(Math.ceil(vp.width),Math.ceil(vp.height));await p.render({canvasContext:c.getContext('2d'),viewport:vp,background:'white'}).promise;return {c,width:v.width,height:v.height}}
function boxBlur(gray,w,h,r){let temp=new Float32Array(w*h),out=new Float32Array(w*h);for(let y=0;y<h;y++){let sum=0;for(let x=-r;x<=r;x++)sum+=gray[y*w+Math.max(0,Math.min(w-1,x))];for(let x=0;x<w;x++){temp[y*w+x]=sum/(2*r+1);sum+=gray[y*w+Math.min(w-1,x+r+1)]-gray[y*w+Math.max(0,x-r)]}}for(let x=0;x<w;x++){let sum=0;for(let y=-r;y<=r;y++)sum+=temp[Math.max(0,Math.min(h-1,y))*w+x];for(let y=0;y<h;y++){out[y*w+x]=sum/(2*r+1);sum+=temp[Math.min(h-1,y+r+1)*w+x]-temp[Math.max(0,y-r)*w+x]}}return out}
function process(src,s){let c=canvas(src.width,src.height),ctx=c.getContext('2d');ctx.drawImage(src,0,0);let image=ctx.getImageData(0,0,c.width,c.height),a=image.data,w=c.width,h=c.height;
 if(s.clean||s.brightness!==100||s.contrast!==100||s.sharpness||s.mode!=='color'){
  let gray=null,bg=null;
  if(s.clean){gray=new Float32Array(w*h);for(let i=0,j=0;i<a.length;i+=4,j++)gray[j]=.299*a[i]+.587*a[i+1]+.114*a[i+2];bg=boxBlur(gray,w,h,Math.max(5,Math.round(w/60)))}
  let amount=s.clean/100,b=s.brightness/100,k=s.contrast/100;
  for(let i=0,j=0;i<a.length;i+=4,j++){
   for(let z=0;z<3;z++){let value=a[i+z];if(bg)value=value*(1-amount)+Math.min(255,value*255/Math.max(100,bg[j]))*amount;a[i+z]=Math.max(0,Math.min(255,(value*b-128)*k+128))}
   if(s.mode!=='color'){let value=.299*a[i]+.587*a[i+1]+.114*a[i+2];if(s.mode==='bw')value=value>175?255:0;a[i]=a[i+1]=a[i+2]=value}
  }
  if(s.sharpness){let original=new Uint8ClampedArray(a),strength=s.sharpness/100;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let i=(y*w+x)*4;for(let z=0;z<3;z++){let mean=(original[i-4+z]+original[i+4+z]+original[i-w*4+z]+original[i+w*4+z])/4;a[i+z]=original[i+z]+strength*(original[i+z]-mean)}}}
  ctx.putImageData(image,0,0);
 }
 if(Math.abs(s.angle)<.001)return c;
 let rad=s.angle*Math.PI/180,ow=Math.ceil(w*Math.abs(Math.cos(rad))+h*Math.abs(Math.sin(rad))),oh=Math.ceil(w*Math.abs(Math.sin(rad))+h*Math.abs(Math.cos(rad)));
 let out=canvas(s.framing==='expand'?ow:w,s.framing==='expand'?oh:h),o=out.getContext('2d');o.fillStyle='white';o.fillRect(0,0,out.width,out.height);o.translate(out.width/2,out.height/2);if(s.framing==='fit'){let factor=Math.min(w/ow,h/oh);o.scale(factor,factor)}o.rotate(rad);o.drawImage(c,-w/2,-h/2);return out;
}
async function preview(load=false){if(!pdf)return;let n=++seq;try{if(load||!baseCanvas){let r=await render(page,100,true);if(n!==seq)return;baseCanvas=r.c;$('original').src=baseCanvas.toDataURL('image/jpeg',.9);$('original').hidden=false}let out=process(baseCanvas,current());if(n!==seq)return;$('corrected').src=out.toDataURL('image/jpeg',.9);$('corrected').hidden=false}catch(e){status(e.message)}}
function change(k,v){if(!pdf||busy)return;config[page]={...current(),[k]:['mode','framing'].includes(k)?v:Math.max(+$(k).min,Math.min(+$(k).max,+v||0))};controls();clearTimeout(timer);timer=setTimeout(()=>preview(),100)}
for(let k of Object.keys(D))$(k).addEventListener('input',e=>change(k,e.target.value));$('angleRange').oninput=e=>change('angle',e.target.value);$('minus').onclick=()=>change('angle',+(current().angle-.1).toFixed(2));$('plus').onclick=()=>change('angle',+(current().angle+.1).toFixed(2));$('grid').onchange=e=>$('correctedPaper').classList.toggle('grid',e.target.checked);
async function go(i){if(busy)return;clearTimeout(timer);page=i;baseCanvas=null;controls();await preview(true)}$('prev').onclick=()=>go(Math.max(0,page-1));$('next').onclick=()=>go(Math.min(count-1,page+1));
$('upload').onchange=async e=>{let f=e.target.files[0];if(!f)return;if(f.size>250*1024*1024){status('파일은 250MB 이하로 선택해 주세요.');return}locked(true);status('브라우저에서 PDF를 읽는 중…');try{let bytes=new Uint8Array(await f.arrayBuffer());await PDFLib.PDFDocument.load(bytes);let next=await pdfjsLib.getDocument({data:bytes.slice(),isEvalSupported:false}).promise;if(pdf)await pdf.destroy();pdf=next;inputBytes=bytes;count=pdf.numPages;page=0;config={};baseCanvas=null;name=f.name;$('filename').textContent=name;$('filename').style.wordBreak='break-all';$('pages').replaceChildren();for(let i=0;i<count;i++){let b=document.createElement('button');b.textContent=`${i+1} 페이지`;b.dataset.page=i;b.onclick=()=>go(i);$('pages').appendChild(b)}$('empty').hidden=$('empty2').hidden=true;controls();await preview(true);status(`${count}페이지를 열었습니다. 파일은 서버에 전송되지 않습니다.`)}catch(e){status(/encrypt|password/i.test(e.message)?'암호가 걸린 PDF는 암호를 해제한 사본을 넣어 주세요.':'PDF 열기 실패: '+e.message)}finally{locked(false);e.target.value=''}};
function yieldUI(){return new Promise(r=>setTimeout(r,0))}
async function deskew(src){let scale=Math.min(1,700/Math.max(src.width,src.height)),w=Math.round(src.width*scale),h=Math.round(src.height*scale),c=canvas(w,h),ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(src,0,0,w,h);let a=ctx.getImageData(0,0,w,h).data,points=[];for(let y=Math.ceil(h/30);y<h-h/30;y++)for(let x=Math.ceil(w/30);x<w-w/30;x++){let i=(y*w+x)*4;if(.299*a[i]+.587*a[i+1]+.114*a[i+2]<165)points.push([x-w/2,y-h/2])}if(points.length<150)return 0;
 function score(deg){let rad=deg*Math.PI/180,co=Math.cos(rad),si=Math.sin(rad),rows=new Float32Array(h+Math.ceil(w*.2)+10),offset=rows.length/2;for(let [x,y] of points){let row=Math.round(x*si+y*co+offset);if(row>0&&row<rows.length)rows[row]++}let sum=0;for(let i=1;i<rows.length;i++)sum+=(rows[i]-rows[i-1])**2;return sum/rows.length}
 let best=0,value=score(0),baseline=value;for(let angle=-5;angle<=5.001;angle+=.25){let scoreValue=score(angle);if(scoreValue>value){value=scoreValue;best=angle}}let center=best;for(let angle=Math.max(-5,center-.25);angle<=Math.min(5,center+.25)+.001;angle+=.05){let scoreValue=score(angle);if(scoreValue>value){value=scoreValue;best=angle}}return value<baseline*1.04||Math.abs(best)<.075?0:+best.toFixed(2);
}
async function automatic(all){if(!pdf||busy)return;locked(true);clearTimeout(timer);try{let targets=all?Array.from({length:count},(_,i)=>i):[page];for(let i=0;i<targets.length;i++){status(`자동 기울기 보정 ${i+1} / ${targets.length}…`);await yieldUI();let {c}=await render(targets[i],75,true),angle=await deskew(c);config[targets[i]]={...(config[targets[i]]||D),angle}}controls();await preview();status('자동 기울기 보정 완료. 글줄과 표를 보고 결과를 확인하세요.')}catch(e){status(e.message)}finally{locked(false)}}$('auto').onclick=()=>automatic(false);$('autoAll').onclick=()=>automatic(true);
$('cleanPreset').onclick=()=>{if(!pdf)return;config[page]={...current(),brightness:105,contrast:115,sharpness:25,clean:35};controls();preview();status('기본 정리값을 적용했습니다. 연한 글자·도장을 확인하세요.')};$('applyAll').onclick=()=>{if(!pdf)return;let s={...current()};for(let i=0;i<count;i++)config[i]={...s};controls();preview();status('각도를 포함한 현재 설정을 전체에 적용했습니다.')};$('reset').onclick=()=>{if(!pdf)return;delete config[page];controls();preview();status('현재 페이지 원본 설정으로 복귀')};$('resetAll').onclick=()=>{if(!pdf)return;config={};controls();preview();status('전체 페이지 원본 설정으로 복귀')};
$('save').onclick=async()=>{if(!pdf||busy)return;locked(true);clearTimeout(timer);try{let source=await PDFLib.PDFDocument.load(inputBytes),out=await PDFLib.PDFDocument.create();for(let i=0;i<count;i++){status(`PDF 저장 준비 ${i+1} / ${count}…`);await yieldUI();let s=config[i]||D;if(JSON.stringify(s)===JSON.stringify(D)){let [p]=await out.copyPages(source,[i]);out.addPage(p);continue}let r=await render(i,+$('dpi').value),c=process(r.c,s),image=await out.embedPng(c.toDataURL('image/png')),w=r.width,h=r.height;if(s.framing==='expand'){w*=c.width/r.c.width;h*=c.height/r.c.height}let p=out.addPage([w,h]);p.drawImage(image,{x:0,y:0,width:w,height:h})}let bytes=await out.save(),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=name.replace(/\.pdf$/i,'')+'_보정.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status('완료! 다운로드 폴더에서 보정된 PDF를 확인하세요.')}catch(e){status('저장 실패: '+e.message)}finally{locked(false)}};
